-- ============================================================================
-- V1__Create_initial_schema.sql
-- Création du schéma initial d'Ubom
-- ============================================================================

-- Table USERS
-- Représente les utilisateurs de l'application
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- Index sur email et username pour les recherches rapides
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);


-- Table PRODUCT_CATEGORY
-- Catégories de produits (Électronique, Maison, Livres, etc.)
CREATE TABLE product_category (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

-- Index pour les soft-delete queries
CREATE INDEX idx_product_category_deleted_at ON product_category(deleted_at);


-- Table PRODUCT
-- Produits en watchlist
CREATE TABLE product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT fk_product_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_product_category_id FOREIGN KEY (category_id) REFERENCES product_category(id)
);

-- Indexes pour optimiser les requêtes fréquentes
CREATE INDEX idx_product_user_id ON product(user_id);
CREATE INDEX idx_product_category_id ON product(category_id);
CREATE INDEX idx_product_deleted_at ON product(deleted_at);


-- Table PRODUCT_PRICE
-- Historique des prix pour chaque produit
CREATE TABLE product_price (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(10, 2) NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_product_price_product_id FOREIGN KEY (product_id) REFERENCES product(id)
);

-- Indexes pour les requêtes d'historique
CREATE INDEX idx_product_price_product_id ON product_price(product_id);
CREATE INDEX idx_product_price_recorded_at ON product_price(recorded_at);
CREATE INDEX idx_product_price_deleted_at ON product_price(deleted_at);