# # Stage 1 : build angular application 
ARG NODE_VERSION=24.14.0-alpine 
# ARG NGINX_VERISON=alpine3.22 

# # use lightweight Node.js image for building 
# FROM node:${NODE_VERSION} AS builder 

# # set the working directory inside container 
# WORKDIR /app 

# # copy package-related files first to leverage Docker's caching mechanism
# COPY package.json *package-lock.json* ./ 

# # install project dependencies using npm ci (ensure a clean, reproductible install)
# RUN --mount=type=cache, target=/root/.npm npm ci 

# # copy the rest of the application source code into the container 
# COPY . . 

# # build angular application 
# RUN npm run buid 

# ################################################
# # Stage 2: Prepare Nginx to Serve Static Files #
# ################################################
# FROM nginxinc/nginx-unprivileged:${NGINX_VERSION} AS runner

# # Copy custom Nginx config 
# COPY nginx.conf /etc/nginx/nginx.conf

# # Copy the static build output from the build stage to Nginx's default HTML serving directory
# COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html

# # Use a built-in non-root user for security best practices
# USER nginx

# # Expose port 8080 to allow HTTP traffic
# # Note: The default Nginx container now listens on port 8080 instead of 80
# EXPOSE 8080

# # Start Nginx directly with custom config
# ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
# CMD ["-g", "daemon off;"]


# --------------------------
FROM node:${NODE_VERSION}
# FROM ghcr.io/pnpm/pnpm:11 
# RUN pnpm runtime set node 24 -g

# active corepack for use pnpm 
RUN corepack enable

WORKDIR /app 

COPY package.json pnpm-lock.yaml ./

COPY . .

EXPOSE 4200 

CMD ["pnpm", "watch", "--", "--host", "0.0.0.0"]

# RUN pnpm install -g @angular/cli 

# RUN pnpm install 

# CMD ["ng", "serve", "--host", "0.0.0.0"]