spring.application.name=backend

# support reading from .env file 
spring.config.import=file:.env[.properties]
# variable for database with R2DBC
# spring.r2dbc.name=${POSTGRES_DB}
# spring.r2dbc.username=${POSTGRES_USER}
# spring.r2dbc.password=${POSTGRES_PASSWORD}
# spring.r2dbc.host=${POSTGRES_HOST}
# spring.r2dbc.port=${POSTGRES_PORT}
# spring.r2dbc.url=r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

# variable for databse with JDBC/JPA
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# only for dev -> use spring.jpa.hibernate.ddl-auto=validate
# for register migrate, need to use Flyway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

# debug serveur
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG

